cart/urls.py
from . import views
from django.urls import path

app_name='cart'
urlpatterns = [
    path('', views.cartpage, name = 'cart'),
    path('addvaluetocart/', views.addvaluetocart, name = 'addvaluetocart'),
    path('removevaluetocart/', views.removevaluetocart, name = 'removevaluetocart'),
]

ecom_website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('details/', include('detailpage.urls')),
    path('cart/', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from detailpage.models import ProductModel, PrimaryCategoryModel
from django.shortcuts import render
from detailpage.models import ProductModel


def get_products_in_cart(request):
    keys = request.session.keys()
    products =[]
    for key in keys:
        id =request.session.get(key)
        try:
            products_in_cart = ProductModel.objects.get(slug=id)
            products.append(products_in_cart)
        except:
            pass
    return products

def get_total_products_quantiy(request):
    id = get_products_in_cart(request)
    products_quantity =[]
    for product in id:
        try:
            quantiy_per_product = request.session[f'product_{product.slug}_quantity']
            products_quantity.append(quantiy_per_product)
        except:
            pass
    return products_quantity

def get_price(request):

    price = []

    products_in_cart = get_products_in_cart(request)
    products_quantity_in_cart = get_total_products_quantiy(request)
    mylists = zip(products_in_cart, products_quantity_in_cart)
    for product,quantity in mylists:
        price.append(product.selling_price*quantity)
    return price


def cartpage(request):
    value = sum(get_total_products_quantiy(request))
    products_in_cart = get_products_in_cart(request)
    products_quantity_in_cart = get_total_products_quantiy(request)
    price = get_price(request)
    mylists = zip(products_in_cart, products_quantity_in_cart,price)
    total_cost=sum(get_price(request))
    category = PrimaryCategoryModel.objects.all()
    context = {
        'mylist':mylists,
        'total_cost':total_cost,
        'categories':category,
        'cart_item_count':value,
    }
    if value == 0:
        return render(request, 'cart/cart_no_products.html', context)
    else:
        return render(request, 'cart/cart.html', context)

def addvaluetocart(request):

    id = request.POST['product_id']
    if request.session.get(f'product_{id}_quantity', False): 
        request.session[f'product_{id}'] = id
        request.session[f'product_{id}_quantity'] += 1
        products_in_cart = get_products_in_cart(request)
        products_quantity_in_cart = get_total_products_quantiy(request)
        price = get_price(request)
        mylists = zip(products_in_cart, products_quantity_in_cart,price)
        total_cost=sum(get_price(request))
        context = {
            'mylist':mylists,
            'total_cost':total_cost,
        }
        return render(request, r'snippets/cards.html', context)
    else:
        request.session[f'product_{id}'] = id
        request.session[f'product_{id}_quantity'] = 1
        products_in_cart = get_products_in_cart(request)
        products_quantity_in_cart = get_total_products_quantiy(request)
        price = get_price(request)
        mylists = zip(products_in_cart, products_quantity_in_cart,price)
        total_cost=sum(get_price(request))
        context = {
            'mylist':mylists,
            'total_cost':total_cost,
        }
        return render(request, r'snippets/cards.html', context)


def removevaluetocart(request):
    id = request.POST['product_id']
    if request.session.get(f'product_{id}_quantity', False):

        if int(request.session[f'product_{id}_quantity']) > 1 :
            request.session[f'product_{id}'] = id
            request.session[f'product_{id}_quantity'] -= 1
            products_in_cart = get_products_in_cart(request)
            products_quantity_in_cart = get_total_products_quantiy(request)
            price = get_price(request)
            mylists = zip(products_in_cart, products_quantity_in_cart,price)
            total_cost=sum(get_price(request))
            context = {
                'mylist':mylists,
                'total_cost':total_cost,
            }
            return render(request, r'snippets/cards.html', context)
        else:
            try:
                del request.session[f'product_{id}']
                del request.session[f'product_{id}_quantity']
                products_in_cart = get_products_in_cart(request)
                products_quantity_in_cart = get_total_products_quantiy(request)
                price = get_price(request)
                mylists = zip(products_in_cart, products_quantity_in_cart,price)
                total_cost=sum(get_price(request))
                context = {
                    'mylist':mylists,
                    'total_cost':total_cost,
                }
                if products_quantity_in_cart:
                    return render(request, r'snippets/cards.html', context)
                else:
                    return render(request, r'snippets/no_products.html', context)

                
            except:

                products_in_cart = get_products_in_cart(request)
                products_quantity_in_cart = get_total_products_quantiy(request)
                price = get_price(request)
                mylists = zip(products_in_cart, products_quantity_in_cart,price)
                total_cost=sum(get_price(request))
                context = {
                    'mylist':mylists,
                    'total_cost':total_cost,
                }
                return render(request, r'snippets/no_products.html', context)
    else:

        products_in_cart = get_products_in_cart(request)
        products_quantity_in_cart = get_total_products_quantiy(request)
        price = get_price(request)
        mylists = zip(products_in_cart, products_quantity_in_cart,price)
        total_cost=sum(get_price(request))
        context = {
            'mylist':mylists,
            'total_cost':total_cost,
        }
        return render(request, r'snippets/no_products.html', context)

cart/templates/snippets/add_or_delete.html
{% include 'snippets/plus_button.html' %}
{% include 'snippets/minus_button.html' %}

cart/templates/snippets/cards.html
<div class="row">
  <div class="col-8">
    <div class="container">
      <div id="cartcontents" class="row row-cols-1">
        {% for product, quantity, price in mylist %}
          <div id= class="col p-2">
            <div class="row border-bottom pb-2">
              <div class="col-md-auto"><img src="{{product.thumbnail.url}}" id="product_thumbnail" alt="..."></div>
              <div class="col">
                <div class="row">
                  <p>{{product.name}} </span></p>
                </div>
                <div class="row">
                  <p>${{product.selling_price}}</p>
                </div>
              </div>
              <div class="col-md-auto pt-4 pb-4">
                <p> Quantity: {{quantity}} </p>
              </div>
              <div class="col-md-auto pt-4 pb-4">
                <p> Total: ${{price}} </p>
              </div>
              <div class="col-md-auto">
                {% include 'snippets/add_or_delete.html' %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="col-4">
    <div class="container">
      <!-- Stack the columns on mobile by making one full-width and the other half-width -->
      <div class="row border-bottom">
        <div class="col-md-12 "> <h3 class="text-center">Checkout</h3></div>
      </div>
    
      <!-- Columns start at 50% wide on mobile and bump up to 33.3% wide on desktop -->
      <div class="row mt-4 mb-4 border-bottom">
        <div class="col-12"><p>Total Cost : ${{total_cost}}</p></div>
      </div>
    
      <!-- Columns are always 50% wide, on mobile and desktop -->
      <div class="row">
        <div class="col-6 "><a href="/" ><button  class="btn btn-success">Checkout</button></a></div>
        <div class="col-6"><a href="/" ><button  class="btn btn-success">Make Payment</button></a></div>
      </div>
    </div>
  </div>
</div>

cart/templates/snippets/minus_button.html
<div class="col-md-auto d-inline-flex p-3 " hx-post="{% url 'cart:removevaluetocart' %}"  hx-vals='{"product_id": "{{product.slug}}"}' hx-target="#cartcontents" hx-swap="innerHTML">
  <button type="button" class="btn btn-secondary">
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-circle" viewBox="0 0 16 16">
<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"></path>
<path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"></path>
</svg>
</button>
</div>

cart/templates/snippets/no_products.html
<div class="row">
  <div class="col-8">
    <div class="container">
      <div class="row row-cols-1">
       <p class="h2 text-center"> No products In Cart </p>
      </div>
    </div>
  </div>
  <div class="col-4">
    <div class="container">
      <div class="row row-cols-1">
        <div class="col">
          <a href="/" ><button  class="btn btn-success px-auto" type="submit">Add Products</button></a>
        </div>
      </div>
    </div>
  </div>
</div>

cart/templates/snippets/plus_button.html
<div class="col-md-auto d-inline-flex pt-3 pb-3" hx-post="{% url 'cart:addvaluetocart' %}"  hx-vals='{"product_id": "{{product.slug}}"}' hx-target="#cartcontents" hx-swap="innerHTML" >
  <button class="btn btn-secondary">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"></path>
<path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"></path>
</svg>
  </button>
</div>