cart/urls.py
from . import views
from django.urls import path

app_name='cart'
urlpatterns = [
    path('', views.cartpage, name = 'cart'),
    path('addvaluetocart/', views.addvaluetocart, name = 'addvaluetocart'),
    path('removevaluetocart/', views.removevaluetocart, name = 'removevaluetocart'),
]

detailpage/urls.py
from . import views
from django.urls import path

app_name ='detailpage'
urlpatterns = [
    path('addvaluetocart/', views.addvaluetocart, name = 'addvaluetocart'),
    path('removevaluetocart/', views.removevaluetocart, name = 'removevaluetocart'),
    path('<slug:slug>/', views.detailpage, name = 'detailpage'),
]

ecom_website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('details/', include('detailpage.urls')),
    path('cart/', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from . import views
from django.urls import path


app_name = 'homepage'
urlpatterns = [
    path( "home/<int:page>",views.listing,name="terms-by-page"),
    path('', views.homepage, name ='homepage'),
    path('sort/', views.sort, name ='sort'),
    path('buynow/<slug:slug>/', views.buynow, name ='buynow'),
    path('addtocart/', views.addtocart, name ='addvaluetocart'),
    path('category/', views.category, name ='category'),
    path('primary/<int:id>/', views.primary, name ='primary'),
    path('secondary/<int:id>/', views.secondary, name ='secondary'),
    
]

detailpage/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.
secondary_category = models.CharField(max_length=100)

class PrimaryCategoryModel(models.Model):

    primary_category = models.CharField(max_length=100, null=True)
    category_header = models.ImageField(upload_to='category', null=True, height_field=None, width_field=None, max_length=None)

    class Meta:
        verbose_name ="Primary Category"
        verbose_name_plural ="Primary Categories"

    def __str__(self):
        return self.primary_category

    def get_absolute_url(self):
        return reverse("PrimaryCategoryModel_detail", kwargs={"pk": self.pk})

class SecondaryCategoryModel(models.Model):

    Secondary_category = models.CharField(max_length=100, null=True)

    class Meta:
        verbose_name ="Secondary Category"
        verbose_name_plural ="Secondary Categories"

    def __str__(self):
        return self.Secondary_category

    def get_absolute_url(self):
        return reverse("SecondaryCategoryModel_detail", kwargs={"pk": self.pk})



class ProductModel(models.Model):

    name = models.CharField(max_length=100)
    slug = models.SlugField(default='', null=False, db_index=True)
    mrp = models.IntegerField(null=False)
    selling_price = models.IntegerField(null=False)
    details = models.TextField(null=False)
    availability = models.BooleanField()
    total_stock = models.IntegerField(null=False)
    primary_category = models.ForeignKey(PrimaryCategoryModel, on_delete=models.CASCADE, null=True)
    secondary_category = models.ForeignKey(SecondaryCategoryModel, on_delete=models.CASCADE, null=True)
    thumbnail = models.ImageField( upload_to='thumbnails', height_field=None, width_field=None, max_length=None, null=True)
    product_image_1 = models.ImageField( upload_to='product_image', height_field=None, width_field=None, max_length=None, null=True)
    product_image_2 = models.ImageField( upload_to='product_image', height_field=None, width_field=None, max_length=None, null=True)
    product_image_3 = models.ImageField( upload_to='product_image', height_field=None, width_field=None, max_length=None, null=True)

    class Meta:
        verbose_name = "Prduct"
        verbose_name_plural ="Products"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("ProductModel_detail", kwargs={"pk": self.pk})

detailpage/views.py
from django.http import HttpResponse
from django.shortcuts import render
from detailpage.models import ProductModel, PrimaryCategoryModel
from homepage.models import HomepageImage


def detailpage(request, slug):
    product = ProductModel.objects.get(slug=slug)
    discount = int((product.selling_price/product.mrp)*100)
    value = sum(get_total_products_quantiy(request))
    hpbanner = HomepageImage.objects.get(pk=2)
    category = PrimaryCategoryModel.objects.all()
    context = {
        'product':product,
        'cart_item_count':value,
        'discount':discount,
        'hpbanner':hpbanner,
        'categories':category,
    }
    
    return render(request, 'detailpage/detailpage.html',context)

def get_products_in_cart(request):
    keys = request.session.keys()
    products =[]
    for key in keys:
        id =request.session.get(key)
        try:
            products_in_cart = ProductModel.objects.get(slug=id)
            products.append(products_in_cart)
        except:
            pass
    return products

def get_total_products_quantiy(request):
    id = get_products_in_cart(request)
    products_quantity =[]
    for product in id:
        try:
            quantiy_per_product = request.session[f'product_{product.slug}_quantity']
            products_quantity.append(quantiy_per_product)
        except:
            pass
    return products_quantity

def addvaluetocart(request):
    id = request.POST['product_id']
    if request.session.get(f'product_{id}_quantity', False): 
        request.session[f'product_{id}'] = id
        request.session[f'product_{id}_quantity'] += 1

        return HttpResponse(sum(get_total_products_quantiy(request)))  
    else:
        request.session[f'product_{id}'] = id
        request.session[f'product_{id}_quantity'] = 1
  
        return HttpResponse(sum(get_total_products_quantiy(request)))

def removevaluetocart(request):
    id = request.POST['product_id']
    if request.session.get(f'product_{id}_quantity', False):

        if int(request.session[f'product_{id}_quantity']) > 1 :
            request.session[f'product_{id}'] = id
            request.session[f'product_{id}_quantity'] -= 1

            return HttpResponse(sum(get_total_products_quantiy(request)))
        else:
            try:
                del request.session[f'product_{id}']
                del request.session[f'product_{id}_quantity']
                return HttpResponse(sum(get_total_products_quantiy(request)))
            except:

                return HttpResponse(sum(get_total_products_quantiy(request)))
    else:
        return HttpResponse(sum(get_total_products_quantiy(request)))



            
        

    





   
   

detailpage/templates/detailpage/.detailpage.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.88.1">
  <title>Shopping Website</title>
  <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/offcanvas-navbar/">
  <link href="{% static "assets/dist/css/bootstrap.min.css" %}" rel="stylesheet">
  <style>
    #details {
      text-align: justify;
      text-justify: inter-word;
    }
  </style>
  <link href="{% static 'offcanvas.css' %}" rel="stylesheet">
  <link href="{% static 'sidebars.css' %}" rel="stylesheet">
  <script src="https://unpkg.com/htmx.org@1.8.4"></script>

</head>

<body class="bg-light" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
  fill="currentColor" class="bi bi-cart2" viewBox="0 0 16 16" style="display: none;">
    <symbol id="speedometer2" viewBox="0 0 16 16">
      <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z" />
    </symbol>
  </svg>

  <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary" aria-label="Main navigation">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">WebShop</a>
      <button class="navbar-toggler p-0 border-0" type="button" id="navbarSideCollapse" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        </ul>
        <form hx-post="{% url 'homepage:sort' %}"  hx-target="#home" hx-swap="div">
          <div class="d-flex flex-row bd-highlight">
            <div class="pe-2 bd-highlight"><a href="/cart/"><button type="button" class="btn btn-outline-light"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag" viewBox="0 0 16 16">
              <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"></path></svg>
                Cart {% include 'snippets/badge.html'  %}
                </button>
            </div></a>
          </div>
        </form>
      </div>
    </div>
  </nav>
  

  <div class="row">

    <div class="col-5 order-First">
      <div class="container mb-2 mt-2">
        {% include 'detailpage/snippets/carousel.html' %}
      </div>
    </div>

    <div class="col order-Second">

      <div class="nav-scroller bg-body shadow-sm mb-2">
        <nav class="nav nav-underline" aria-label="Secondary navigation">
          <a class="nav-link" aria-current="page" href="#">{{product.primary_category}}</a>
          <a class="nav-link" href="#">{{product.secondary_category}}</a>
        </nav>
      </div>

      <div class="container">
        <div class="row row-cols-1">
          <div class="col border-bottom">
            <h1>{{product.name}}</h1>
          </div>
          <div class="col border-bottom mt-2 mb-2">
            <p class='h3'>

              <small class="text-success">
              <mark class="text-success" >{{discount}}% off </mark>
              </small>

              <small class="text-danger">
              <s>${{product.mrp}}</s>
              </small>

              <small class="text-success">
                ${{product.selling_price}}
              </small>

            </p>
          </div>
          <div class="col">
              {% csrf_token %}
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 border-bottom mb-1">
                <input type="hidden" name="slug" value="{{product.slug}}">
                {% include 'detailpage/snippets/add_or_delete.html' %}
                <a href="{% url 'homepage:buynow' product.slug %}"><div class="col mt-3 mb-3 "><button type="button" class="btn btn-success">Buy Now</button></div></a>
              </div>
          <div class="col border-bottom">
            <h2>Details</h2>
            <p id="details">{{product.details}}</p>
          </div>
          <div class="col fs-3">

            {% if product.total_stock <= 0 or product.availability == False %}
            <p>Out Of Stock</p>
            {% else %}
            <p>{{product.total_stock}} left in Stock</p>
            {% endif %}

            
          </div>
        </div>
      </div>

    </div>


  </div>

  </main>
  <script src="{% static 'assets\dist\js\bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'offcanvas.js' %}"></script>
  <script src="{% static 'sidebars.js' %}"></script>
</body>

</html>

detailpage/templates/detailpage/detailpage.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Shopping Website</title>
     
    <style>
      #hpimage {
              max-width: 30%;
              height: 100%;
            }
    </style>
  </head>


  <div class="row border">
    <div class="col-10 mx-auto mb-3">
      <a class="navbar-brand" href="/"><img id ="hpimage" src="{{hpbanner.hpimage.url}}" class="d-block m-auto" alt="..."></a>
    </div>
  </div>

  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">WebShop</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Category
            </a>
            <ul class="dropdown-menu">
              {% for category in categories %}
              <li><a class="dropdown-item" href="{% url 'homepage:primary' category.pk %}">{{category.primary_category}}</a></li>
              {% endfor %}
            </ul>
          </li>
          <li class="nav-item">
            <a href="/cart/" class="nav-link">Your cart ( {% include 'snippets/badge.html'  %} )</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

    <div class="row mt-3 mb">
      <div class="col-10  mx-auto">
        <div class="container text-center">
          <div class="row row-cols-3">
              {% for product in products %}
                <div class="col m-2">
                  <div class="card h-100 text-decoration-none link-dark"><a class="text-decoration-none link-dark" href="{% url 'detailpage:detailpage' product.slug %}">
                    <img src="{{product.thumbnail.url}}" class="card-img-top p-2 img-thumbnail" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">
                        {{product.name}}
                      </h5>
                      <h5 class="card-title">
                        ${{product.selling_price}}
                      </h5>
                      <p class="card-text mb-2">
                        {{product.details | truncatechars:60}}
                      </p></a>
                    </div>
                  </div>
                </div>
              {% endfor %}
          </div>
        </div>
      </div>
    </div>

    <div class="row">

      <div class="col-5 order-First">
        <div class="container mb-2 mt-2">
          {% include 'detailpage/snippets/carousel.html' %}
        </div>
      </div>
  
      <div class="col order-Second">
  
        <div class="nav-scroller bg-body shadow-sm mb-2">
          <nav class="nav nav-underline" aria-label="Secondary navigation">
            <a class="nav-link" aria-current="page" href="{% url 'homepage:primary' product.primary_category.pk %}">{{product.primary_category}}</a>
            <p class="nav-link">/</p>
            <a class="nav-link" href="{% url 'homepage:secondary' product.secondary_category.pk %}">{{product.secondary_category}}</a>
          </nav>
        </div>
  
        <div class="container">
          <div class="row row-cols-1">
            <div class="col border-bottom mb-2">
              <h1>{{product.name}}</h1>
            </div>
            <div class="col border-bottom mt-2 mb-2">
              <p class='h3'>
  
                <small class="text-success">
                <mark class="text-success" >{{discount}}% off </mark>
                </small>
  
                <small class="text-danger">
                <s>${{product.mrp}}</s>
                </small>
  
                <small class="text-success">
                  ${{product.selling_price}}
                </small>
  
              </p>
            </div>
            <div class="col">
                {% csrf_token %}
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 border-bottom mb-1">
                  <input type="hidden" name="slug" value="{{product.slug}}">
                  {% include 'detailpage/snippets/add_or_delete.html' %}
                  <a href="{% url 'homepage:buynow' product.slug %}"><div class="col mt-3 mb-3 "><button type="button" class="btn btn-success">Buy Now</button></div></a>
                </div>
            <div class="col border-bottom">
              <h2>Details</h2>
              <p id="details">{{product.details}}</p>
            </div>
            <div class="col fs-3">  
              {% if product.total_stock <= 0 or product.availability == False %}
              <p>Out Of Stock</p>
              {% else %}
              <p>{{product.total_stock}} left in Stock</p>
              {% endif %}           
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="https://unpkg.com/htmx.org@1.8.4"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </body>
  <footer class="text-center border-top mt-5">
    <p>All rights Reserved ®️</p>
  </footer>
</html>