cart/urls.py
from . import views
from django.urls import path

app_name='cart'
urlpatterns = [
    path('', views.cartpage, name = 'cart'),
    path('addvaluetocart/', views.addvaluetocart, name = 'addvaluetocart'),
    path('removevaluetocart/', views.removevaluetocart, name = 'removevaluetocart'),
]

ecom_website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('details/', include('detailpage.urls')),
    path('cart/', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from . import views
from django.urls import path


app_name = 'homepage'
urlpatterns = [
    path( "home/<int:page>",views.listing,name="terms-by-page"),
    path('', views.homepage, name ='homepage'),
    path('sort/', views.sort, name ='sort'),
    path('buynow/<slug:slug>/', views.buynow, name ='buynow'),
    path('addtocart/', views.addtocart, name ='addvaluetocart'),
    path('category/', views.category, name ='category'),
    path('primary/<int:id>/', views.primary, name ='primary'),
    path('secondary/<int:id>/', views.secondary, name ='secondary'),
    
]

homepage/models.py
from django.db import models

# Create your models here.
class HomepageImage(models.Model):

    hpimage = models.ImageField(upload_to='homepage_image', null="true", height_field=None, width_field=None, max_length=None)

    class Meta:
        verbose_name = "Homepage Image"
        verbose_name_plural ="Homepage Image"

    def __str__(self):
        name='Homepage Image'
        return name

 

homepage/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from detailpage.models import ProductModel, PrimaryCategoryModel, SecondaryCategoryModel
from django.db.models import Q
from detailpage.views import addvaluetocart
from .models import HomepageImage
from django.core.paginator import Paginator, EmptyPage


def get_products_in_cart(request):
    keys = request.session.keys()
    products =[]
    for key in keys:
        id =request.session.get(key)
        try:
            products_in_cart = ProductModel.objects.get(slug=id)
            products.append(products_in_cart)
        except:
            pass
    return products

def get_total_products_quantiy(request):
    id = get_products_in_cart(request)
    products_quantity =[]
    for product in id:
        try:
            quantiy_per_product = request.session[f'product_{product.slug}_quantity']
            products_quantity.append(quantiy_per_product)
        except:
            pass
    return products_quantity

def get_price(request):

    price = []

    products_in_cart = get_products_in_cart(request)
    products_quantity_in_cart = get_total_products_quantiy(request)
    mylists = zip(products_in_cart, products_quantity_in_cart)
    for product,quantity in mylists:
     
        price.append(product.selling_price*quantity)
    return price

def addvaluetocarthp(request,slug):

    id = slug
    if request.session.get(f'product_{id}_quantity', False): 
        request.session[f'product_{id}'] = id
        request.session[f'product_{id}_quantity'] += 1
        products_in_cart = get_products_in_cart(request)
        products_quantity_in_cart = get_total_products_quantiy(request)
        price = get_price(request)
        mylists = zip(products_in_cart, products_quantity_in_cart,price)
        total_cost=sum(get_price(request))
        context = {
            'mylist':mylists,
            'total_cost':total_cost,
        }
        return render(request, r'snippets/cards.html', context)
    else:
        request.session[f'product_{id}'] = id
        request.session[f'product_{id}_quantity'] = 1
        products_in_cart = get_products_in_cart(request)
        products_quantity_in_cart = get_total_products_quantiy(request)
        price = get_price(request)
        mylists = zip(products_in_cart, products_quantity_in_cart,price)
        total_cost=sum(get_price(request))
        context = {
            'mylist':mylists,
            'total_cost':total_cost,
        }
        return render(request, r'snippets/cards.html', context)

def get_products_in_cart(request):
    keys = request.session.keys()
    products =[]
    for key in keys:
        id =request.session.get(key)
        try:
            products_in_cart = ProductModel.objects.get(slug=id)
            products.append(products_in_cart)
        except:
            pass
    return products

def get_total_products_quantiy(request):
    id = get_products_in_cart(request)
    products_quantity =[]
    for product in id:
        try:
            quantiy_per_product = request.session[f'product_{product.slug}_quantity']
            products_quantity.append(quantiy_per_product)
        except:
            pass
    return products_quantity


def sort(request):
    value = sum(get_total_products_quantiy(request))
    hpimage = HomepageImage.objects.get(pk=1)
    hpbanner = HomepageImage.objects.get(pk=2)
    category = PrimaryCategoryModel.objects.all()
    search_term = (request.POST.get('search',None))
    products = ProductModel.objects.filter(Q(name__contains=search_term)|Q(details__contains=search_term))
    context = {
        'products':products,
        'categories':category,   
        'cart_item_count':value,
        'hpimage':hpimage,
        'hpbanner':hpbanner,
        'categories':category,
    }
    if len(products) == 0:
        return render(request, 'homepage/snippets/homepage_search_no_result.html', context)
    else:
        return render(request, 'homepage/snippets/homepage_search.html', context)
    

def category(request):

    search_term = (request.POST.get('category'))
    products = PrimaryCategoryModel.objects.all()
    context = {
        'products':category,
    }
    return render(request, 'homepage/snippets/cards.html', context)

def primary(request, id):

    primary_category = PrimaryCategoryModel.objects.get(id=id)
    products_in_category = primary_category.productmodel_set.all()
    value = sum(get_total_products_quantiy(request))
    category = PrimaryCategoryModel.objects.all()
    hpimage = HomepageImage.objects.get(pk=1)
    categoryimage = PrimaryCategoryModel.objects.get(pk=1)
    hpbanner = HomepageImage.objects.get(pk=2)
    context = {
        'products':products_in_category,
        'cart_item_count':value,
        'hpimage':hpimage,
        'hpbanner':hpbanner,
        'categories':category,
        'current_category':primary_category,
    }
    
    if len(products_in_category) == 0:
        return render(request, 'homepage/snippets/homepage_search_no_result.html', context)
    else:
        return render(request, 'homepage/snippets/homepage_search.html', context)

def secondary(request, id):

    category = SecondaryCategoryModel.objects.get(id=id)
    products_in_category = category.productmodel_set.all()
    value = sum(get_total_products_quantiy(request))
    category = PrimaryCategoryModel.objects.all()
    secondary = SecondaryCategoryModel.objects.get(id=id)
    hpimage = HomepageImage.objects.get(pk=1)
    hpbanner = HomepageImage.objects.get(pk=2)
    categoryimage = PrimaryCategoryModel.objects.get(pk=1)
    context = {
        'products':products_in_category,
        'cart_item_count':value,
        'secondary':secondary,
        'hpimage':hpimage,
        'hpbanner':hpbanner,
        'categories':category,
        'category_image':categoryimage,
    }
    
    if len(products_in_category) == 0:
        return render(request, 'homepage/snippets/no_result_secondary.html', context)
    else:
        return render(request, 'homepage/snippets/search_secondary.html', context)

def buynow(request,slug):
    addvaluetocarthp(request,slug)
    return redirect('cart:cart')

def addtocart(request):
    addvaluetocart(request)
    return HttpResponse(sum(get_total_products_quantiy(request))) 

def listing(request, page):
    value = sum(get_total_products_quantiy(request))
    products = ProductModel.objects.all()
    category = PrimaryCategoryModel.objects.all()
    hpimage = HomepageImage.objects.get(pk=1)
    hpbanner = HomepageImage.objects.get(pk=2)
    paginator = Paginator(products, per_page=6)
    try:
        page_object = paginator.page(page)
    except EmptyPage:
        page_object = paginator.page(1)
    context = {
        'products':products,
        'cart_item_count':value,
        'hpimage':hpimage,
        'hpbanner':hpbanner,
        'categories':category,
        "page_obj": page_object
    }
    return render(request, 'homepage/index_pagenation.html', context)

def homepage(request):   
    value = sum(get_total_products_quantiy(request))
    products = ProductModel.objects.all()
    category = PrimaryCategoryModel.objects.all()
    hpimage = HomepageImage.objects.get(pk=1)
    hpbanner = HomepageImage.objects.get(pk=2)
    paginator = Paginator(products, per_page=6)
    page_object = paginator.page(1)
    context = {
        'products':products,
        'cart_item_count':value,
        'hpimage':hpimage,
        'hpbanner':hpbanner,
        'categories':category,
        "page_obj": page_object
    }
    return render(request, 'homepage/index_pagenation.html', context)

homepage/templates/homepage/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Shopping Website</title>
    <script src="https://unpkg.com/htmx.org@1.8.4"></script>
     
    <style>
      #hpimage {
              max-width: 50%;
              height: 100%;
            }
    </style>
    <style>
      #hpimage1 {
              max-width: 30%;
              height: 100%;
            }
    </style>
  </head>
  <div class="row border">
    <div class="col-10 mx-auto mb-3">
      <a class="navbar-brand" href="/"><img id ="hpimage1" src="{{hpbanner.hpimage.url}}" class="d-block m-auto" alt="..."></a>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg bg-light"cat>
    <div class="container-fluid">
      <a class="navbar-brand" href="/">WebShop</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Category
            </a>
            <ul class="dropdown-menu">
              {% for category in categories %}
              <li><a class="dropdown-item" href="{% url 'homepage:primary' category.pk %}">{{category.primary_category}}</a></li>
              {% endfor %}
            </ul>
          </li>
          <li class="nav-item">
            <a href="/cart/" class="nav-link">Your cart ( {% include 'snippets/badge.html'  %} )</a>
          </li>
        </ul>
        <form hx-post="{% url 'homepage:sort' %}"  hx-target="#home" hx-swap="div" class="d-flex" role="search">
          <input name="search" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

<body  hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  <div id="home">
    <div class="row border">
      <div class="col-10 mx-auto mb-3">
        <img id ="hpimage"src="{{hpimage.hpimage.url}}" class="d-block m-auto" alt="...">
      </div>
    </div>
    <div class="row mt-3 mb-5">
      
     {% include 'homepage/snippets/cards.html' %}
    </div>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </body>
  <footer class="text-center border-top mt-5">
    <p>All rights Reserved ®️</p>
  </footer>
</html>

homepage/templates/homepage/index_pagenation.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Shopping Website</title>
    <script src="https://unpkg.com/htmx.org@1.8.4"></script>
     
    <style>
      #hpimage {
              max-width: 100%;
              height: 100%;
            }
    </style>
    <style>
      #hpimage1 {
              max-width: 30%;
              height: 100%;
            }
    </style>
  </head>
  <div class="row border">
    <div class="col-10 mx-auto mb-3">
      <a class="navbar-brand" href="/"><img id ="hpimage1" src="{{hpbanner.hpimage.url}}" class="d-block m-auto" alt="..."></a>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg bg-light"cat>
    <div class="container-fluid">
      <a class="navbar-brand" href="/">WebShop</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Category
            </a>
            <ul class="dropdown-menu">
              {% for category in categories %}
              <li><a class="dropdown-item" href="{% url 'homepage:primary' category.pk %}">{{category.primary_category}}</a></li>
              {% endfor %}
            </ul>
          </li>
          <li class="nav-item">
            <a href="/cart/" class="nav-link">Your cart ( {% include 'snippets/badge.html'  %} )</a>
          </li>
        </ul>
        <form method = "post" action="{% url 'homepage:sort' %}" class="d-flex" role="search">
          {% csrf_token %}
          <input name="search" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

<body  hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  <div id="home">
    <div class="row border">
      <div class="col-12 mx-auto mb-3">
        <svg class="bd-placeholder-img card-img-top" width="100%" height="300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><image href="{{hpimage.hpimage.url}}" height="100%" width="100%" preserveAspectRatio="xMidYMid slice" /></svg>
      </div>
    </div>
    <div class="row mt-2 mb-5">
     {% include 'homepage/snippets/cards.html' %}
    </div>
  
      <div class="col-12 mb-3" align="center">
        {% block pagination %}
      {% for page_number in page_obj.paginator.get_elided_page_range %}
          {% if page_number == page_obj.paginator.ELLIPSIS %}
              {{page_number}}
          {% else %}
              <a
                  href="{% url 'homepage:terms-by-page' page_number %}"
                  class="{% if page_number == page_obj.number %}current{% endif %}"
              >
              <button class="btn btn-outline-success" type="submit">{{page_number}}</button> 
              </a>
          {% endif %}
      {% endfor %}
    {% endblock %}
      </div>
  
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <footer class="text-center border-top mt-5">
      <p>All rights Reserved ®️</p>
    </footer>
  </div>
  </body>

</html>