cart/urls.py
from . import views
from django.urls import path

app_name='cart'
urlpatterns = [
    path('', views.cartpage, name = 'cart'),
    path('addvaluetocart/', views.addvaluetocart, name = 'addvaluetocart'),
    path('removevaluetocart/', views.removevaluetocart, name = 'removevaluetocart'),
]

detailpage/urls.py
from . import views
from django.urls import path

app_name ='detailpage'
urlpatterns = [
    path('addvaluetocart/', views.addvaluetocart, name = 'addvaluetocart'),
    path('removevaluetocart/', views.removevaluetocart, name = 'removevaluetocart'),
    path('<slug:slug>/', views.detailpage, name = 'detailpage'),
]

ecom_website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('details/', include('detailpage.urls')),
    path('cart/', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

detailpage/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.
secondary_category = models.CharField(max_length=100)

class PrimaryCategoryModel(models.Model):

    primary_category = models.CharField(max_length=100, null=True)
    category_header = models.ImageField(upload_to='category', null=True, height_field=None, width_field=None, max_length=None)

    class Meta:
        verbose_name ="Primary Category"
        verbose_name_plural ="Primary Categories"

    def __str__(self):
        return self.primary_category

    def get_absolute_url(self):
        return reverse("PrimaryCategoryModel_detail", kwargs={"pk": self.pk})

class SecondaryCategoryModel(models.Model):

    Secondary_category = models.CharField(max_length=100, null=True)

    class Meta:
        verbose_name ="Secondary Category"
        verbose_name_plural ="Secondary Categories"

    def __str__(self):
        return self.Secondary_category

    def get_absolute_url(self):
        return reverse("SecondaryCategoryModel_detail", kwargs={"pk": self.pk})



class ProductModel(models.Model):

    name = models.CharField(max_length=100)
    slug = models.SlugField(default='', null=False, db_index=True)
    mrp = models.IntegerField(null=False)
    selling_price = models.IntegerField(null=False)
    details = models.TextField(null=False)
    availability = models.BooleanField()
    total_stock = models.IntegerField(null=False)
    primary_category = models.ForeignKey(PrimaryCategoryModel, on_delete=models.CASCADE, null=True)
    secondary_category = models.ForeignKey(SecondaryCategoryModel, on_delete=models.CASCADE, null=True)
    thumbnail = models.ImageField( upload_to='thumbnails', height_field=None, width_field=None, max_length=None, null=True)
    product_image_1 = models.ImageField( upload_to='product_image', height_field=None, width_field=None, max_length=None, null=True)
    product_image_2 = models.ImageField( upload_to='product_image', height_field=None, width_field=None, max_length=None, null=True)
    product_image_3 = models.ImageField( upload_to='product_image', height_field=None, width_field=None, max_length=None, null=True)

    class Meta:
        verbose_name = "Prduct"
        verbose_name_plural ="Products"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("ProductModel_detail", kwargs={"pk": self.pk})

detailpage/views.py
from django.http import HttpResponse
from django.shortcuts import render
from detailpage.models import ProductModel, PrimaryCategoryModel
from homepage.models import HomepageImage


def detailpage(request, slug):
    product = ProductModel.objects.get(slug=slug)
    discount = int((product.selling_price/product.mrp)*100)
    value = sum(get_total_products_quantiy(request))
    hpbanner = HomepageImage.objects.get(pk=2)
    category = PrimaryCategoryModel.objects.all()
    context = {
        'product':product,
        'cart_item_count':value,
        'discount':discount,
        'hpbanner':hpbanner,
        'categories':category,
    }
    
    return render(request, 'detailpage/detailpage.html',context)

def get_products_in_cart(request):
    keys = request.session.keys()
    products =[]
    for key in keys:
        id =request.session.get(key)
        try:
            products_in_cart = ProductModel.objects.get(slug=id)
            products.append(products_in_cart)
        except:
            pass
    return products

def get_total_products_quantiy(request):
    id = get_products_in_cart(request)
    products_quantity =[]
    for product in id:
        try:
            quantiy_per_product = request.session[f'product_{product.slug}_quantity']
            products_quantity.append(quantiy_per_product)
        except:
            pass
    return products_quantity

def addvaluetocart(request):
    id = request.POST['product_id']
    if request.session.get(f'product_{id}_quantity', False): 
        request.session[f'product_{id}'] = id
        request.session[f'product_{id}_quantity'] += 1

        return HttpResponse(sum(get_total_products_quantiy(request)))  
    else:
        request.session[f'product_{id}'] = id
        request.session[f'product_{id}_quantity'] = 1
  
        return HttpResponse(sum(get_total_products_quantiy(request)))

def removevaluetocart(request):
    id = request.POST['product_id']
    if request.session.get(f'product_{id}_quantity', False):

        if int(request.session[f'product_{id}_quantity']) > 1 :
            request.session[f'product_{id}'] = id
            request.session[f'product_{id}_quantity'] -= 1

            return HttpResponse(sum(get_total_products_quantiy(request)))
        else:
            try:
                del request.session[f'product_{id}']
                del request.session[f'product_{id}_quantity']
                return HttpResponse(sum(get_total_products_quantiy(request)))
            except:

                return HttpResponse(sum(get_total_products_quantiy(request)))
    else:
        return HttpResponse(sum(get_total_products_quantiy(request)))



            
        

    





   
   

detailpage/templates/detailpage/snippets/add_or_delete.html
{% include 'detailpage/snippets/plus_button.html' %}
{% include 'detailpage/snippets/minus_button.html' %}

detailpage/templates/detailpage/snippets/carousel.html
{% load static %}
<div id="carouselExampleIndicators" class="carousel carousel-dark slide" data-bs-ride="false">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{product.product_image_1.url}}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{{product.product_image_2.url}}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{{product.product_image_3.url}}" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

detailpage/templates/detailpage/snippets/minus_button.html
<div class="col-md-auto d-inline-flex pt-3 pb-3" hx-post="{% url 'detailpage:removevaluetocart' %}"  hx-vals='{"product_id": "{{product.slug}}"}' hx-target="#cartbadge" hx-swap="span">{% csrf_token %}<button type="button" class="btn btn-secondary">
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-circle" viewBox="0 0 16 16">
<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"></path>
<path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"></path>
</svg>
</button>
</div>

detailpage/templates/detailpage/snippets/plus_button.html
<div class="col-md-auto d-inline-flex pt-3 pb-3" hx-post="{% url 'detailpage:addvaluetocart' %}"  hx-vals='{"product_id": "{{product.slug}}"}' hx-target="#cartbadge" hx-swap="span" >
  <button class="btn btn-secondary">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"></path>
<path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"></path>
</svg>
  </button>
</div>